index:
    path: /
    controller: App\Controller\DefaultController:index
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
docs:
    path: /{path}
    controller: App\Controller\DefaultController:docs
    requirements:
      path: .*